site_name: 'Dev 4uRest'
theme:
  name: 'material'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.keys

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js'
  - 'https://cdn.jsdelivr.net/npm/svg-pan-zoom@3.6.1/dist/svg-pan-zoom.min.js'


nav:
  - Home: index.md
  - Main Flows:
      - MPF Manage Page : developer_guide/ManagePageFlow.md
      - LAF Login Admin : developer_guide/LoginAdminFlow.md

  - Download Template:
      - UDTF User: developer_guide/DownloadUserTemplateFlow.md
      - PEDTF Permissions: developer_guide/DownloadPermissionsTemplateFlow.md
      - RODTF Roles: developer_guide/DownloadRolesTemplateFlow.md
      - PIDTF Printers: developer_guide/DownloadPrintersTemplateFlow.md
      - PSDTF Points Of Sale: developer_guide/DownloadPointsOfSaleTemplateFlow.md
      - PLDTF Platforms: developer_guide/DownloadPlatformsTemplateFlow.md
      - TADTF Taxes: developer_guide/DownloadTaxesTemplateFlow.md
      - PGDTF P M Groups: developer_guide/DownloadPMGroupsTemplateFlow.md
      - PMDTF Payment Methods: developer_guide/DownloadPaymentMethodsTemplateFlow.md
      - CADTF Categories: developer_guide/DownloadCategoriesTemplateFlow.md
      - PIDTF Products: developer_guide/DownloadProductsTemplateFlow.md

  - Upload Template:
      - UDUTF User: developer_guide/UploadUserTemplateFlow.md
      - PRUTF Permissions: developer_guide/UploadPermissionsTemplateFlow.md
      - ROUTF Roles: developer_guide/UploadRolesTemplateFlow.md
      - PRUTF Printers: developer_guide/UploadPrintersTemplateFlow.md
      - PSUTF Points Of Sale: developer_guide/UploadPointsOfSaleTemplateFlow.md
      - PRUTF Platforms: developer_guide/UploadPlatformsTemplateFlow.md
      - TAUTF Taxes: developer_guide/UploadTaxesTemplateFlow.md
      - PGUTF P M Groups: developer_guide/UploadPMGroupsTemplateFlow.md
      - PMUTF Payment Methods: developer_guide/UploadPaymentMethodsTemplateFlow.md
      - CAUTF Categories: developer_guide/UploadCategoriesTemplateFlow.md
      - PRUTF Product: developer_guide/UploadProductsTemplateFlow.md
